updated the titles on notifications to share the community name directly
alkem-io/notifications pull request #122
Opened 2022-05-31 13:56 UTC by techsmyth

Many of the notifications did not make clear from which community / context they come - so did that in a consistent way.

2022-06-02 12:19 UTC, valentinyanakiev requested changes
As general feedback - I don't think this is an update, but rather a downgrade to what we have. It is moving away from something easily human-readable to something machine-readable.

I don't see how ```Your application to COMMUNITY_XXX was received!``` is worse than ```[COMMUNITY_XXX] Application to join received!```.

Also, user registration doesn't have a community in the payload, so that won't work at all.

I believe an UX discussion would benefit us before we jump in and do this.

2022-06-02 12:19 UTC, valentinyanakiev commented on src/templates/user.registration.admin.js
> +    '[{{community.name}}] Admin - New user registration: {{registrant.name}}',
there is no community in this payload

2022-06-03 09:42 UTC, techsmyth commented on src/templates/user.registration.admin.js
> +    '[{{community.name}}] Admin - New user registration: {{registrant.name}}',
Fixed

2022-09-09 14:29 UTC, larssondenise approved these changes

2022-09-09 14:34 UTC, merged