Add community collaboration interest notifications.
alkem-io/notifications pull request #132
Opened 2022-07-05 08:20 UTC by alstojanovic

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-07-05 12:06 UTC, hero101 requested changes
Unable to test due to missing migration for user preference.

2022-07-05 12:06 UTC, hero101 commented on src/services/domain/builders/community-collaboration-interest/community.collaboration.interest.notification.builder.ts
> +
empty line

2022-07-08 15:13 UTC, alstojanovic commented on src/common/dto/community.collaboration.interest.payload.ts
> +export type CommunityCollaborationInterestPayload = {
The server now matches this.

2022-07-08 15:14 UTC, alstojanovic commented on src/common/constants/events.ts
> +  'communityCollaborationInterest';
The server now matches this.

2022-07-11 06:36 UTC, hero101 requested changes
The build is failing.

2022-07-11 06:36 UTC, hero101 commented on src/common/dto/community.collaboration.interest.payload.ts
> +export type CommunityCollaborationInterestPayload = {
> The server now matches this.
The type of `communityName` does not match the type in the server.

2022-07-11 06:36 UTC, hero101 commented on notifications.yml
> +    - name: admin
I still do not believe `GLOBAL_ADMIN_COMMUNITY` to be required here.

2022-07-11 07:12 UTC, alstojanovic commented on notifications.yml
> +    - name: admin
Removed that the notifications admin as well.

2022-07-11 08:51 UTC, merged