Event payloads cleaned up; email payloads cleaned up; renaming; new notification; additional infomration
alkem-io/notifications pull request #162
Opened 2022-12-02 21:05 UTC by techsmyth

Significant clean up of the notifications payloads, naming + information that is passed.

Event payloads now inherit from some shared base types
Email payloads also now inherit from some shared base types

Naming updated to be consistent across the service

Added event for platform user removed

Added additional information as being expected for generating urls related to callouts / cards. 

...

2022-12-08 15:44 UTC, Comoque1 commented
Error is thrown, when for notification on application
![image](https://user-images.githubusercontent.com/23620658/206491278-99543cfe-2fb9-4edd-829d-f02252330af4.png)

2022-12-09 08:52 UTC, valentinyanakiev requested changes
- All template types should be constants, e.g. `community_application_created`. It is used in multiple places and changing one will break others, e.g. the tests.
- (Can be done later) - the wrong pattern is used for typings. You have used complex inheritance hierarchy while this is crying out loud for `composition` over `inheritance`. `Composition` will make the code way less error prone and much more re-usable. It will also be easy to add this. 
- There are some outdated names, please look inline.
- (For later, requires a couple of stories on the backlog...) The `community_application_created` admin template + flow doesn't make sense to me. The flow should redirect the admin to the `user` **APPLICATION**, and not the `user` **PROFILE**, e.g.
![image](https://user-images.githubusercontent.com/7090348/206662679-65c7cf25-c4ed-45c6-9856-0a3eb3bdde37.png)
This will require updated routing on the client to the admin community page applications. I believe this flow will make a lot more sense than what we have now and will be much better admin user experience.

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/collaboration-callout-published/collaboration.callout.published.notification.builder.ts
>        entityID:
It is worth using `journeyID` instead of `entityID` everywhere, if we are committed to switching to that terminology.

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/collaboration-card-created/collaboration.card.created.notification.builder.ts
> +      entityID:
Same principle as suggested before, `journeyID` instead of `entityID`
```suggestion
      journeyID:
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
> +    const hubURL = this.alkemioUrlGenerator.createPlatformURL();
```suggestion
    const alkemioURL = this.alkemioUrlGenerator.createPlatformURL();
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/communication-update-created/communication.update.created.notification.builder.ts
>          url: hubURL,
```suggestion
        url: alkemioURL,
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
> +    const hubURL = this.alkemioUrlGenerator.createPlatformURL();
```suggestion
    const alkemioURL = this.alkemioUrlGenerator.createPlatformURL();
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
>          url: hubURL,
```suggestion
        url: alkemioURL,
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
> +    const hubURL = this.alkemioUrlGenerator.createPlatformURL();
```suggestion
    const alkemioURL = this.alkemioUrlGenerator.createPlatformURL();
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-new-member/community.new.member.notification.builder.ts
>          url: hubURL,
```suggestion
        url: alkemioURL,
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/platform-user-registered/platform.user.registered.notification.builder.ts
> +    const hubURL = this.alkemioUrlGenerator.createPlatformURL();
```suggestion
    const alkemioURL = this.alkemioUrlGenerator.createPlatformURL();
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/platform-user-registered/platform.user.registered.notification.builder.ts
>          url: hubURL,
```suggestion
        url: alkemioURL,
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
> +    const communityURL = this.alkemioUrlGenerator.createJourneyURL(
```suggestion
    const journeyURL = this.alkemioUrlGenerator.createJourneyURL(
```

2022-12-09 08:52 UTC, valentinyanakiev commented on service/src/services/domain/builders/community-application-created/community.application.created.notification.builder.ts
>          url: communityURL,
```suggestion
        url: journeyURL,
```

2022-12-09 09:15 UTC, Comoque1 commented
Body of email sent, when user join a community, don't have the community as link.
![image](https://user-images.githubusercontent.com/23620658/206667123-02391270-2f94-4d74-b08f-bdcbf3657dc0.png)

![image](https://user-images.githubusercontent.com/23620658/206667257-ecb0a790-5dd3-4038-91ed-14ab62af9b5d.png)

2022-12-09 14:34 UTC, valentinyanakiev approved these changes

2022-12-09 14:39 UTC, merged